#file system- create and read any file

'''with open('10 apri.py','r')as file:
    a = file.read()
    print(a)'''

#for write in file

'''with open("s.py","w")as file:
    file.write("print('Hello world')")'''
    
'''with open("s.py","w")as file:
    file.write("/nprint('This is an append data')")'''

#/n is used for break the line and write in next line.


    
'''with open('23 april.py', 'r')as file:
    a= file.read()
    print(a)
with open('22 april','r')as file:
    a = file.read()
    print(a)'''

with open('anjali.py','w')as file:
    file.write("print('Hello Anjali')")
    
with open('anjali.py','w')as file:
    file.write("print('please work properly')")
    
    
